name: CD deploy

on:
    push:
        branches:
            - test_go

env:
    SOURCE_FOLDER: '/root/go/src/'

jobs:
    branch_build_test:
        runs-on: besanh
        steps:
            - uses: actions/checkout@v4
            - name: Setup go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.x'
            - name: Install depencencies
              run: go get .

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
    branch_deploy:
        runs-on: besanh
        steps:
            - name: deploy source
              run: |
                  cd ${{ env.SOURCE_FOLDER }}
                  git pull
                  go get .
                  go get -u
                  go build
            - name: Notify
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN}}
                message: |
                    Repository:
                        [link](https://github.com/${{ github.repository}}
                    Branch:
                        ${{ github.ref_name }}
                    Actor:
                        ${{ github.actor }}
                    Commit:
                        Message: ${{ github.event_name}} - ${{ github.event.commits[0].message }} - [link](https://github.com/${{ github.repository }}/commit/${{github.sha}})