name: Notify source code golang from commit

on:
    push:
        branches:
            - test_go
    pull_request:
        branches:
            - test_go

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: send message to telegram
              uses: appleboy/telegram-action@master
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN}}
                message: |
                    Repository:
                        [link](https://github.com/${{ github.repository}}
                    Branch:
                        ${{ github.ref_name }}
                    Actor:
                        ${{ github.actor }}
                    Commit:
                        Message: ${{ github.event_name}} - ${{ github.event.commits[0].message }} - [link](https://github.com/${{ github.repository }}/commit/${{github.sha}}