name: Push commit

on:
    push:
        branches:
            - '*'
jobs:
    notify-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Telegram Message Notify
              uses: appleboy/telegram-action@v1.0.0
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                format: markdown
                message: |
                    Repository:
                        ${{ github.repository }} [links] https://github.com/${{ github.repository }}
                    Branch:
                        ${{ github.ref }}
                    Actor:
                        ${{ github.actor }}
                    Commit:
                        https://github.com/${{github.repository}}/commit/${{github.sha}}
                    Message:
                        ${{github.event.commits[0].message}}

        